import type { Meta, StoryObj } from '@storybook/react';
import { Select } from './Select';
declare const meta: Meta<typeof Select>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const WithDefaultValue: Story;
export declare const WithError: Story;
export declare const Disabled: Story;
export declare const FullWidth: Story;
export declare const ManyOptions: Story;
